<template>
    <v-main>
        <v-container>
            <v-card flat>
                <v-card-title>
                    <v-btn class="mr-2" icon @click="$refs.calendar.prev()">
                        <v-icon v-text="'mdi-chevron-left'" />
                    </v-btn>
                    <v-btn class="mr-2" icon @click="$refs.calendar.next()">
                        <v-icon v-text="'mdi-chevron-right'" />
                    </v-btn>
                    <span>{{ title }}</span>
                    <v-spacer />
                    <v-btn-toggle>
                        <v-btn small @click="type = 'month'">Mes</v-btn>
                        <v-btn small @click="type = 'week'">Semana</v-btn>
                        <v-btn small @click="type = 'day'">Dia</v-btn>
                    </v-btn-toggle>
                    <!-- <div style="width: 200px">
                        <v-select
                            v-model="type"
                            hide-details
                            item-text="text"
                            item-value="value"
                            :items="[
                                { value: 'month', text: 'Mes' },
                                { value: 'week', text: 'Semana' },
                                { value: 'day', text: 'Dia' },
                            ]"
                            outlined
                        />
                    </div> -->
                </v-card-title>
            </v-card>
            <v-card flat>
                <v-card-text>
                    <v-sheet height="600">
                        <v-calendar ref="calendar" v-model="current" :events="events" :type="type" @click:event="eventController($event)" @click:more="moreController($event)">
                            <template #event="{ event }"> {{ event.name }} </template>
                        </v-calendar>
                    </v-sheet>
                </v-card-text>
            </v-card>

            <v-dialog v-model="view" max-width="400">
                <v-card>
                    <v-card-title>
                        <span>{{ event.license_plate }}</span>
                        <v-spacer />
                        <v-btn icon @click="view = false">
                            <v-icon v-text="'mdi-close'" />
                        </v-btn>
                    </v-card-title>
                    <v-divider />
                    <v-card-text>
                        <div class=""></div>
                    </v-card-text>
                </v-card>
            </v-dialog>

            <pre>{{ event }}</pre>
        </v-container>
    </v-main>
</template>

<script lang="ts">
    import Vue from 'vue'

    // import { DateTime } from 'luxon'

    export default Vue.extend({
        layout: 'dashboard',

        data() {
            return {
                type: 'month',
                view: false,
                current: '',
                event: {} as any,
                events: [] as any[],
                title: '',
                data: {
                    detail: [
                        {
                            fuel_transaction_code: '43be77db',
                            license_plate: '378076',
                            volume: 14.76,
                            amount: 24498.7,
                            fuel_provider: 'Delta Panamá',
                            provider: null,
                            transaction_order: '86852',
                            transaction_datetime: '2021-06-10 15:42:25',
                            comment: 'El vehículo no cuenta con un dispositivo de GPS o el dispositivo no esta reportando.',
                            transaction_status: 'Transacción inconsistente',
                            odometer: '25954490.00',
                            gps_event: '2019-10-16 06:48:51',
                            address: 'Morelos',
                            account_name: null,
                            google_link: 'https://maps.google.com/?q=9.0313600,-79.5066400',
                            code: 'ad8f',
                            fuel_type: '',
                            fuel_provider_code: '8add',
                            cost_per_volume_unit: 1659.8,
                            distance: null,
                            distance_per_volume_unit: null,
                            cost_per_distance_unit: null,
                        },
                        {
                            fuel_transaction_code: '5fefb97e',
                            license_plate: '378076',
                            volume: 14.76,
                            amount: 24498.7,
                            fuel_provider: 'Delta Panamá',
                            provider: null,
                            transaction_order: '86852',
                            transaction_datetime: '2021-06-10 15:42:25',
                            comment: 'El vehículo no cuenta con un dispositivo de GPS o el dispositivo no esta reportando.',
                            transaction_status: 'Transacción para revisar',
                            odometer: '25954490.00',
                            gps_event: '2019-10-16 07:08:45',
                            address: 'Monte Oscuro',
                            account_name: null,
                            google_link: 'https://maps.google.com/?q=9.0313600,-79.5066400',
                            code: 'c4b2',
                            fuel_type: '',
                            fuel_provider_code: '8add',
                            cost_per_volume_unit: 1659.8,
                            distance: 0,
                            distance_per_volume_unit: 0,
                            cost_per_distance_unit: null,
                        },
                        {
                            fuel_transaction_code: '16bb2274',
                            license_plate: '378076',
                            volume: 14.76,
                            amount: 24498.7,
                            fuel_provider: 'Delta Panamá',
                            provider: null,
                            transaction_order: '86852',
                            transaction_datetime: '2021-06-10 15:42:25',
                            comment: 'El vehículo no cuenta con un dispositivo de GPS o el dispositivo no esta reportando.',
                            transaction_status: 'Transacción para revisar',
                            odometer: '25954490.00',
                            gps_event: '2019-10-16 07:40:34',
                            address: 'Monte Oscuro',
                            account_name: null,
                            google_link: 'https://maps.google.com/?q=9.0313600,-79.5066400',
                            code: 'c4b2',
                            fuel_type: '',
                            fuel_provider_code: '8add',
                            cost_per_volume_unit: 1659.8,
                            distance: 0,
                            distance_per_volume_unit: 0,
                            cost_per_distance_unit: null,
                        },
                        {
                            fuel_transaction_code: '4ac4675f',
                            license_plate: '378076',
                            volume: 14.76,
                            amount: 24498.7,
                            fuel_provider: 'Delta Panamá',
                            provider: null,
                            transaction_order: '86852',
                            transaction_datetime: '2021-06-10 15:42:25',
                            comment: 'El vehículo no cuenta con un dispositivo de GPS o el dispositivo no esta reportando.',
                            transaction_status: 'Transacción para revisar',
                            odometer: '25954490.00',
                            gps_event: '2019-08-19 12:49:13',
                            address: 'CALLE DON BOSCO, BARRIOS UNIDOS,  AGUADULCE,  COCLE',
                            account_name: null,
                            google_link: 'https://maps.google.com/?q=9.0313600,-79.5066400',
                            code: 'c4b2',
                            fuel_type: '',
                            fuel_provider_code: '8add',
                            cost_per_volume_unit: 1659.8,
                            distance: 0,
                            distance_per_volume_unit: 0,
                            cost_per_distance_unit: null,
                        },
                        {
                            fuel_transaction_code: '1c6f468d',
                            license_plate: '378076',
                            volume: 14.76,
                            amount: 24498.7,
                            fuel_provider: 'Delta Panamá',
                            provider: null,
                            transaction_order: '86852',
                            transaction_datetime: '2021-06-10 15:42:25',
                            comment: 'El vehículo no cuenta con un dispositivo de GPS o el dispositivo no esta reportando.',
                            transaction_status: 'Transacción para revisar',
                            odometer: '25954490.00',
                            gps_event: '2019-10-16 08:45:10',
                            address: 'Chame',
                            account_name: null,
                            google_link: 'https://maps.google.com/?q=9.0313600,-79.5066400',
                            code: 'c4b2',
                            fuel_type: '',
                            fuel_provider_code: '8add',
                            cost_per_volume_unit: 1659.8,
                            distance: 0,
                            distance_per_volume_unit: 0,
                            cost_per_distance_unit: null,
                        },
                        {
                            fuel_transaction_code: 'f87e5f68',
                            license_plate: '378076',
                            volume: 14.76,
                            amount: 24498.7,
                            fuel_provider: 'Delta Panamá',
                            provider: null,
                            transaction_order: '86852',
                            transaction_datetime: '2021-06-10 15:42:25',
                            comment: 'El vehículo no cuenta con un dispositivo de GPS o el dispositivo no esta reportando.',
                            transaction_status: 'Transacción para revisar',
                            odometer: '25954490.00',
                            gps_event: '2019-10-16 09:04:40',
                            address: 'Monte Oscuro',
                            account_name: null,
                            google_link: 'https://maps.google.com/?q=9.0313600,-79.5066400',
                            code: 'c4b2',
                            fuel_type: '',
                            fuel_provider_code: '8add',
                            cost_per_volume_unit: 1659.8,
                            distance: 0,
                            distance_per_volume_unit: 0,
                            cost_per_distance_unit: null,
                        },
                        {
                            fuel_transaction_code: '9c9f840f',
                            license_plate: '378076',
                            volume: 14.76,
                            amount: 24498.7,
                            fuel_provider: 'Delta Panamá',
                            provider: null,
                            transaction_order: '86852',
                            transaction_datetime: '2021-06-10 15:42:25',
                            comment: 'El vehículo no cuenta con un dispositivo de GPS o el dispositivo no esta reportando.',
                            transaction_status: 'Transacción para revisar',
                            odometer: '25954490.00',
                            gps_event: '2019-10-16 09:50:33',
                            address: 'Los Robles',
                            account_name: null,
                            google_link: 'https://maps.google.com/?q=9.0313600,-79.5066400',
                            code: 'c4b2',
                            fuel_type: '',
                            fuel_provider_code: '8add',
                            cost_per_volume_unit: 1659.8,
                            distance: 0,
                            distance_per_volume_unit: 0,
                            cost_per_distance_unit: null,
                        },
                        {
                            fuel_transaction_code: '9674d246',
                            license_plate: '378076',
                            volume: 14.76,
                            amount: 24498.7,
                            fuel_provider: 'Delta Panamá',
                            provider: null,
                            transaction_order: '86852',
                            transaction_datetime: '2021-06-10 15:42:25',
                            comment: 'El vehículo no cuenta con un dispositivo de GPS o el dispositivo no esta reportando.',
                            transaction_status: 'Transacción para revisar',
                            odometer: '25954490.00',
                            gps_event: '2019-10-16 10:58:48',
                            address: 'San Antonio',
                            account_name: null,
                            google_link: 'https://maps.google.com/?q=9.0313600,-79.5066400',
                            code: 'c4b2',
                            fuel_type: '',
                            fuel_provider_code: '8add',
                            cost_per_volume_unit: 1659.8,
                            distance: 0,
                            distance_per_volume_unit: 0,
                            cost_per_distance_unit: null,
                        },
                        {
                            fuel_transaction_code: '5d415c1b',
                            license_plate: 'AU9370',
                            volume: 24.58,
                            amount: 40808.71,
                            fuel_provider: 'Delta Panamá',
                            provider: null,
                            transaction_order: '86848',
                            transaction_datetime: '2021-06-10 14:50:25',
                            comment: null,
                            transaction_status: 'Transacción no validada',
                            odometer: null,
                            gps_event: null,
                            address: null,
                            account_name: null,
                            google_link: null,
                            code: 'e054',
                            fuel_type: '',
                            fuel_provider_code: '8add',
                            cost_per_volume_unit: 1660.24,
                            distance: null,
                            distance_per_volume_unit: null,
                            cost_per_distance_unit: null,
                        },
                        {
                            fuel_transaction_code: '5a131326',
                            license_plate: 'AU9370',
                            volume: 24.58,
                            amount: 40808.71,
                            fuel_provider: 'Delta Panamá',
                            provider: null,
                            transaction_order: '86848',
                            transaction_datetime: '2021-06-10 14:50:25',
                            comment: null,
                            transaction_status: 'Transacción no validada',
                            odometer: null,
                            gps_event: null,
                            address: null,
                            account_name: null,
                            google_link: null,
                            code: 'e054',
                            fuel_type: '',
                            fuel_provider_code: '8add',
                            cost_per_volume_unit: 1660.24,
                            distance: null,
                            distance_per_volume_unit: null,
                            cost_per_distance_unit: null,
                        },
                        {
                            fuel_transaction_code: '4247bf58',
                            license_plate: 'AU9370',
                            volume: 24.58,
                            amount: 40808.71,
                            fuel_provider: 'Delta Panamá',
                            provider: null,
                            transaction_order: '86848',
                            transaction_datetime: '2021-06-10 14:50:25',
                            comment: null,
                            transaction_status: 'Transacción no validada',
                            odometer: null,
                            gps_event: null,
                            address: null,
                            account_name: null,
                            google_link: null,
                            code: 'e054',
                            fuel_type: '',
                            fuel_provider_code: '8add',
                            cost_per_volume_unit: 1660.24,
                            distance: null,
                            distance_per_volume_unit: null,
                            cost_per_distance_unit: null,
                        },
                        {
                            fuel_transaction_code: 'db9ee48b',
                            license_plate: 'AU9370',
                            volume: 24.58,
                            amount: 40808.71,
                            fuel_provider: 'Delta Panamá',
                            provider: null,
                            transaction_order: '86848',
                            transaction_datetime: '2021-06-10 14:50:25',
                            comment: null,
                            transaction_status: 'Transacción no validada',
                            odometer: null,
                            gps_event: null,
                            address: null,
                            account_name: null,
                            google_link: null,
                            code: 'e054',
                            fuel_type: '',
                            fuel_provider_code: '8add',
                            cost_per_volume_unit: 1660.24,
                            distance: null,
                            distance_per_volume_unit: null,
                            cost_per_distance_unit: null,
                        },
                        {
                            fuel_transaction_code: '424b7c9a',
                            license_plate: 'AU9370',
                            volume: 24.58,
                            amount: 40808.71,
                            fuel_provider: 'Delta Panamá',
                            provider: null,
                            transaction_order: '86848',
                            transaction_datetime: '2021-06-10 14:50:25',
                            comment: null,
                            transaction_status: 'Transacción no validada',
                            odometer: null,
                            gps_event: null,
                            address: null,
                            account_name: null,
                            google_link: null,
                            code: 'e054',
                            fuel_type: '',
                            fuel_provider_code: '8add',
                            cost_per_volume_unit: 1660.24,
                            distance: null,
                            distance_per_volume_unit: null,
                            cost_per_distance_unit: null,
                        },
                        {
                            fuel_transaction_code: '55e8853c',
                            license_plate: 'AU9370',
                            volume: 24.58,
                            amount: 40808.71,
                            fuel_provider: 'Delta Panamá',
                            provider: null,
                            transaction_order: '86848',
                            transaction_datetime: '2021-06-10 14:50:25',
                            comment: null,
                            transaction_status: 'Transacción no validada',
                            odometer: null,
                            gps_event: null,
                            address: null,
                            account_name: null,
                            google_link: null,
                            code: 'e054',
                            fuel_type: '',
                            fuel_provider_code: '8add',
                            cost_per_volume_unit: 1660.24,
                            distance: null,
                            distance_per_volume_unit: null,
                            cost_per_distance_unit: null,
                        },
                        {
                            fuel_transaction_code: '155df47b',
                            license_plate: 'AU9370',
                            volume: 24.58,
                            amount: 40808.71,
                            fuel_provider: 'Delta Panamá',
                            provider: null,
                            transaction_order: '86848',
                            transaction_datetime: '2021-06-10 14:50:25',
                            comment: null,
                            transaction_status: 'Transacción no validada',
                            odometer: null,
                            gps_event: null,
                            address: null,
                            account_name: null,
                            google_link: null,
                            code: 'e054',
                            fuel_type: '',
                            fuel_provider_code: '8add',
                            cost_per_volume_unit: 1660.24,
                            distance: null,
                            distance_per_volume_unit: null,
                            cost_per_distance_unit: null,
                        },
                        {
                            fuel_transaction_code: '2250ceaa',
                            license_plate: 'AU9370',
                            volume: 24.58,
                            amount: 40808.71,
                            fuel_provider: 'Delta Panamá',
                            provider: null,
                            transaction_order: '86848',
                            transaction_datetime: '2021-06-10 14:50:25',
                            comment: null,
                            transaction_status: 'Transacción no validada',
                            odometer: null,
                            gps_event: null,
                            address: null,
                            account_name: null,
                            google_link: null,
                            code: 'e054',
                            fuel_type: '',
                            fuel_provider_code: '8add',
                            cost_per_volume_unit: 1660.24,
                            distance: null,
                            distance_per_volume_unit: null,
                            cost_per_distance_unit: null,
                        },
                        {
                            fuel_transaction_code: '667f0e2f',
                            license_plate: 'AX2609',
                            volume: 13.38,
                            amount: 22453.06,
                            fuel_provider: 'Delta Panamá',
                            provider: null,
                            transaction_order: '47022',
                            transaction_datetime: '2021-06-13 17:43:19',
                            comment: 'El vehículo no cuenta con un dispositivo de GPS o el dispositivo no esta reportando.',
                            transaction_status: 'Transacción inconsistente',
                            odometer: '435241540.00',
                            gps_event: '2019-10-16 06:51:08',
                            address: 'CARRETERA INTERAMERICANA & VIA HACIA ATALAYA, SANTIAGO (CAB),  SANTIAGO,  VERAGUAS',
                            account_name: null,
                            google_link: 'https://maps.google.com/?q=8.5366100,-80.3436800',
                            code: 'ad8f',
                            fuel_type: '',
                            fuel_provider_code: '8add',
                            cost_per_volume_unit: 1678.11,
                            distance: null,
                            distance_per_volume_unit: null,
                            cost_per_distance_unit: null,
                        },
                        {
                            fuel_transaction_code: '857b83f9',
                            license_plate: 'AX2609',
                            volume: 13.38,
                            amount: 22453.06,
                            fuel_provider: 'Delta Panamá',
                            provider: null,
                            transaction_order: '47022',
                            transaction_datetime: '2021-06-13 17:43:19',
                            comment: 'El vehículo no cuenta con un dispositivo de GPS o el dispositivo no esta reportando.',
                            transaction_status: 'Transacción para revisar',
                            odometer: '435241540.00',
                            gps_event: '2019-10-16 07:37:47',
                            address: 'Monte Oscuro',
                            account_name: null,
                            google_link: 'https://maps.google.com/?q=8.5366100,-80.3436800',
                            code: 'c4b2',
                            fuel_type: '',
                            fuel_provider_code: '8add',
                            cost_per_volume_unit: 1678.11,
                            distance: 0,
                            distance_per_volume_unit: 0,
                            cost_per_distance_unit: null,
                        },
                        {
                            fuel_transaction_code: '112e438a',
                            license_plate: 'AX2609',
                            volume: 13.38,
                            amount: 22453.06,
                            fuel_provider: 'Delta Panamá',
                            provider: null,
                            transaction_order: '47022',
                            transaction_datetime: '2021-06-13 17:43:19',
                            comment: 'El vehículo no cuenta con un dispositivo de GPS o el dispositivo no esta reportando.',
                            transaction_status: 'Transacción para revisar',
                            odometer: '435241540.00',
                            gps_event: '2019-10-16 06:19:32',
                            address: 'BASE COBRA SAN MIGUELITO, VIA TRANSISTMICA & CALLE SANTA LIBRADA, VICTORIANO LORENZO,  SAN MIGUELITO,  PANAMA',
                            account_name: null,
                            google_link: 'https://maps.google.com/?q=8.5366100,-80.3436800',
                            code: 'c4b2',
                            fuel_type: '',
                            fuel_provider_code: '8add',
                            cost_per_volume_unit: 1678.11,
                            distance: 0,
                            distance_per_volume_unit: 0,
                            cost_per_distance_unit: null,
                        },
                        {
                            fuel_transaction_code: '09982444',
                            license_plate: 'AX2609',
                            volume: 13.38,
                            amount: 22453.06,
                            fuel_provider: 'Delta Panamá',
                            provider: null,
                            transaction_order: '47022',
                            transaction_datetime: '2021-06-13 17:43:19',
                            comment: 'El vehículo no cuenta con un dispositivo de GPS o el dispositivo no esta reportando.',
                            transaction_status: 'Transacción para revisar',
                            odometer: '435241540.00',
                            gps_event: '2019-10-16 08:18:22',
                            address: 'Valbuena',
                            account_name: null,
                            google_link: 'https://maps.google.com/?q=8.5366100,-80.3436800',
                            code: 'c4b2',
                            fuel_type: '',
                            fuel_provider_code: '8add',
                            cost_per_volume_unit: 1678.11,
                            distance: 0,
                            distance_per_volume_unit: 0,
                            cost_per_distance_unit: null,
                        },
                        {
                            fuel_transaction_code: 'dc6b0022',
                            license_plate: 'AX2609',
                            volume: 13.38,
                            amount: 22453.06,
                            fuel_provider: 'Delta Panamá',
                            provider: null,
                            transaction_order: '47022',
                            transaction_datetime: '2021-06-13 17:43:19',
                            comment: 'El vehículo no cuenta con un dispositivo de GPS o el dispositivo no esta reportando.',
                            transaction_status: 'Transacción para revisar',
                            odometer: '435241540.00',
                            gps_event: '2019-10-16 08:50:35',
                            address: 'Bolívar',
                            account_name: null,
                            google_link: 'https://maps.google.com/?q=8.5366100,-80.3436800',
                            code: 'c4b2',
                            fuel_type: '',
                            fuel_provider_code: '8add',
                            cost_per_volume_unit: 1678.11,
                            distance: 0,
                            distance_per_volume_unit: 0,
                            cost_per_distance_unit: null,
                        },
                        {
                            fuel_transaction_code: 'e7a268cf',
                            license_plate: 'AX2609',
                            volume: 13.38,
                            amount: 22453.06,
                            fuel_provider: 'Delta Panamá',
                            provider: null,
                            transaction_order: '47022',
                            transaction_datetime: '2021-06-13 17:43:19',
                            comment: 'El vehículo no cuenta con un dispositivo de GPS o el dispositivo no esta reportando.',
                            transaction_status: 'Transacción para revisar',
                            odometer: '435241540.00',
                            gps_event: '2019-10-16 09:07:13',
                            address: 'Chorrera',
                            account_name: null,
                            google_link: 'https://maps.google.com/?q=8.5366100,-80.3436800',
                            code: 'c4b2',
                            fuel_type: '',
                            fuel_provider_code: '8add',
                            cost_per_volume_unit: 1678.11,
                            distance: 0,
                            distance_per_volume_unit: 0,
                            cost_per_distance_unit: null,
                        },
                        {
                            fuel_transaction_code: 'd2eacd47',
                            license_plate: 'AX2609',
                            volume: 13.38,
                            amount: 22453.06,
                            fuel_provider: 'Delta Panamá',
                            provider: null,
                            transaction_order: '47022',
                            transaction_datetime: '2021-06-13 17:43:19',
                            comment: 'El vehículo no cuenta con un dispositivo de GPS o el dispositivo no esta reportando.',
                            transaction_status: 'Transacción para revisar',
                            odometer: '435241540.00',
                            gps_event: '2019-10-16 10:33:41',
                            address: 'Chorrera',
                            account_name: null,
                            google_link: 'https://maps.google.com/?q=8.5366100,-80.3436800',
                            code: 'c4b2',
                            fuel_type: '',
                            fuel_provider_code: '8add',
                            cost_per_volume_unit: 1678.11,
                            distance: 0,
                            distance_per_volume_unit: 0,
                            cost_per_distance_unit: null,
                        },
                        {
                            fuel_transaction_code: 'a7e98ebc',
                            license_plate: 'AX2609',
                            volume: 13.38,
                            amount: 22453.06,
                            fuel_provider: 'Delta Panamá',
                            provider: null,
                            transaction_order: '47022',
                            transaction_datetime: '2021-06-13 17:43:19',
                            comment: 'El vehículo no cuenta con un dispositivo de GPS o el dispositivo no esta reportando.',
                            transaction_status: 'Transacción para revisar',
                            odometer: '435241540.00',
                            gps_event: '2019-10-16 11:13:29',
                            address: 'CARRETERA INTERAMERICANA, BARRIO COLON,  LA CHORRERA,  PANAMA',
                            account_name: null,
                            google_link: 'https://maps.google.com/?q=8.5366100,-80.3436800',
                            code: 'c4b2',
                            fuel_type: '',
                            fuel_provider_code: '8add',
                            cost_per_volume_unit: 1678.11,
                            distance: 0,
                            distance_per_volume_unit: 0,
                            cost_per_distance_unit: null,
                        },
                        {
                            fuel_transaction_code: '65c58166',
                            license_plate: 'AX2611',
                            volume: 16.47,
                            amount: 27640.66,
                            fuel_provider: 'Delta Panamá',
                            provider: null,
                            transaction_order: '47016',
                            transaction_datetime: '2021-06-13 17:02:32',
                            comment: 'El vehículo no cuenta con un dispositivo de GPS o el dispositivo no esta reportando.',
                            transaction_status: 'Transacción inconsistente',
                            odometer: '525880470.00',
                            gps_event: '2019-10-16 06:47:49',
                            address: 'Valbuena',
                            account_name: null,
                            google_link: 'https://maps.google.com/?q=8.5216400,-80.3646800',
                            code: 'ad8f',
                            fuel_type: '',
                            fuel_provider_code: '8add',
                            cost_per_volume_unit: 1678.24,
                            distance: null,
                            distance_per_volume_unit: null,
                            cost_per_distance_unit: null,
                        },
                        {
                            fuel_transaction_code: 'e06c6770',
                            license_plate: 'AX2611',
                            volume: 16.47,
                            amount: 27640.66,
                            fuel_provider: 'Delta Panamá',
                            provider: null,
                            transaction_order: '47016',
                            transaction_datetime: '2021-06-13 17:02:32',
                            comment: 'El vehículo no cuenta con un dispositivo de GPS o el dispositivo no esta reportando.',
                            transaction_status: 'Transacción para revisar',
                            odometer: '525880470.00',
                            gps_event: '2019-10-16 07:26:53',
                            address: 'Miraflores',
                            account_name: null,
                            google_link: 'https://maps.google.com/?q=8.5216400,-80.3646800',
                            code: 'c4b2',
                            fuel_type: '',
                            fuel_provider_code: '8add',
                            cost_per_volume_unit: 1678.24,
                            distance: 0,
                            distance_per_volume_unit: 0,
                            cost_per_distance_unit: null,
                        },
                        {
                            fuel_transaction_code: '3aab9d45',
                            license_plate: 'AX2611',
                            volume: 16.47,
                            amount: 27640.66,
                            fuel_provider: 'Delta Panamá',
                            provider: null,
                            transaction_order: '47016',
                            transaction_datetime: '2021-06-13 17:02:32',
                            comment: 'El vehículo no cuenta con un dispositivo de GPS o el dispositivo no esta reportando.',
                            transaction_status: 'Transacción para revisar',
                            odometer: '525880470.00',
                            gps_event: '2019-10-16 07:49:55',
                            address: 'Monte Oscuro',
                            account_name: null,
                            google_link: 'https://maps.google.com/?q=8.5216400,-80.3646800',
                            code: 'c4b2',
                            fuel_type: '',
                            fuel_provider_code: '8add',
                            cost_per_volume_unit: 1678.24,
                            distance: 0,
                            distance_per_volume_unit: 0,
                            cost_per_distance_unit: null,
                        },
                        {
                            fuel_transaction_code: '50e1a069',
                            license_plate: 'AX2611',
                            volume: 16.47,
                            amount: 27640.66,
                            fuel_provider: 'Delta Panamá',
                            provider: null,
                            transaction_order: '47016',
                            transaction_datetime: '2021-06-13 17:02:32',
                            comment: 'El vehículo no cuenta con un dispositivo de GPS o el dispositivo no esta reportando.',
                            transaction_status: 'Transacción para revisar',
                            odometer: '525880470.00',
                            gps_event: '2019-10-16 08:13:57',
                            address: 'Delta el Tranque',
                            account_name: null,
                            google_link: 'https://maps.google.com/?q=8.5216400,-80.3646800',
                            code: 'c4b2',
                            fuel_type: '',
                            fuel_provider_code: '8add',
                            cost_per_volume_unit: 1678.24,
                            distance: 0,
                            distance_per_volume_unit: 0,
                            cost_per_distance_unit: null,
                        },
                        {
                            fuel_transaction_code: '4d80884a',
                            license_plate: 'AX2611',
                            volume: 16.47,
                            amount: 27640.66,
                            fuel_provider: 'Delta Panamá',
                            provider: null,
                            transaction_order: '47016',
                            transaction_datetime: '2021-06-13 17:02:32',
                            comment: 'El vehículo no cuenta con un dispositivo de GPS o el dispositivo no esta reportando.',
                            transaction_status: 'Transacción para revisar',
                            odometer: '525880470.00',
                            gps_event: '2019-10-16 08:52:16',
                            address: 'Cáceres',
                            account_name: null,
                            google_link: 'https://maps.google.com/?q=8.5216400,-80.3646800',
                            code: 'c4b2',
                            fuel_type: '',
                            fuel_provider_code: '8add',
                            cost_per_volume_unit: 1678.24,
                            distance: 0,
                            distance_per_volume_unit: 0,
                            cost_per_distance_unit: null,
                        },
                        {
                            fuel_transaction_code: '20791b30',
                            license_plate: 'AX2611',
                            volume: 16.47,
                            amount: 27640.66,
                            fuel_provider: 'Delta Panamá',
                            provider: null,
                            transaction_order: '47016',
                            transaction_datetime: '2021-06-13 17:02:32',
                            comment: 'El vehículo no cuenta con un dispositivo de GPS o el dispositivo no esta reportando.',
                            transaction_status: 'Transacción para revisar',
                            odometer: '525880470.00',
                            gps_event: '2019-10-16 09:09:39',
                            address: 'Expressway',
                            account_name: null,
                            google_link: 'https://maps.google.com/?q=8.5216400,-80.3646800',
                            code: 'c4b2',
                            fuel_type: '',
                            fuel_provider_code: '8add',
                            cost_per_volume_unit: 1678.24,
                            distance: 0,
                            distance_per_volume_unit: 0,
                            cost_per_distance_unit: null,
                        },
                        {
                            fuel_transaction_code: '44486d46',
                            license_plate: 'AX2611',
                            volume: 16.47,
                            amount: 27640.66,
                            fuel_provider: 'Delta Panamá',
                            provider: null,
                            transaction_order: '47016',
                            transaction_datetime: '2021-06-13 17:02:32',
                            comment: 'El vehículo no cuenta con un dispositivo de GPS o el dispositivo no esta reportando.',
                            transaction_status: 'Transacción para revisar',
                            odometer: '525880470.00',
                            gps_event: '2019-10-16 10:09:58',
                            address: '3 de Noviembre',
                            account_name: null,
                            google_link: 'https://maps.google.com/?q=8.5216400,-80.3646800',
                            code: 'c4b2',
                            fuel_type: '',
                            fuel_provider_code: '8add',
                            cost_per_volume_unit: 1678.24,
                            distance: 0,
                            distance_per_volume_unit: 0,
                            cost_per_distance_unit: null,
                        },
                        {
                            fuel_transaction_code: 'a3e979a3',
                            license_plate: 'AX2611',
                            volume: 16.47,
                            amount: 27640.66,
                            fuel_provider: 'Delta Panamá',
                            provider: null,
                            transaction_order: '47016',
                            transaction_datetime: '2021-06-13 17:02:32',
                            comment: 'El vehículo no cuenta con un dispositivo de GPS o el dispositivo no esta reportando.',
                            transaction_status: 'Transacción para revisar',
                            odometer: '525880470.00',
                            gps_event: '2019-10-16 11:07:24',
                            address: 'Nuevo San Juan',
                            account_name: null,
                            google_link: 'https://maps.google.com/?q=8.5216400,-80.3646800',
                            code: 'c4b2',
                            fuel_type: '',
                            fuel_provider_code: '8add',
                            cost_per_volume_unit: 1678.24,
                            distance: 0,
                            distance_per_volume_unit: 0,
                            cost_per_distance_unit: null,
                        },
                        {
                            fuel_transaction_code: '392633e8',
                            license_plate: 'BA8954',
                            volume: 33.73,
                            amount: 56610.37,
                            fuel_provider: 'Delta Panamá',
                            provider: null,
                            transaction_order: '46092',
                            transaction_datetime: '2021-06-10 07:23:15',
                            comment: null,
                            transaction_status: 'Transacción no validada',
                            odometer: null,
                            gps_event: null,
                            address: null,
                            account_name: null,
                            google_link: null,
                            code: 'e054',
                            fuel_type: '',
                            fuel_provider_code: '8add',
                            cost_per_volume_unit: 1678.34,
                            distance: null,
                            distance_per_volume_unit: null,
                            cost_per_distance_unit: null,
                        },
                        {
                            fuel_transaction_code: '9720944b',
                            license_plate: 'BA8954',
                            volume: 33.73,
                            amount: 56610.37,
                            fuel_provider: 'Delta Panamá',
                            provider: null,
                            transaction_order: '46092',
                            transaction_datetime: '2021-06-10 07:23:15',
                            comment: null,
                            transaction_status: 'Transacción no validada',
                            odometer: null,
                            gps_event: null,
                            address: null,
                            account_name: null,
                            google_link: null,
                            code: 'e054',
                            fuel_type: '',
                            fuel_provider_code: '8add',
                            cost_per_volume_unit: 1678.34,
                            distance: null,
                            distance_per_volume_unit: null,
                            cost_per_distance_unit: null,
                        },
                        {
                            fuel_transaction_code: 'd6b83411',
                            license_plate: 'BA8954',
                            volume: 33.73,
                            amount: 56610.37,
                            fuel_provider: 'Delta Panamá',
                            provider: null,
                            transaction_order: '46092',
                            transaction_datetime: '2021-06-10 07:23:15',
                            comment: null,
                            transaction_status: 'Transacción no validada',
                            odometer: null,
                            gps_event: null,
                            address: null,
                            account_name: null,
                            google_link: null,
                            code: 'e054',
                            fuel_type: '',
                            fuel_provider_code: '8add',
                            cost_per_volume_unit: 1678.34,
                            distance: null,
                            distance_per_volume_unit: null,
                            cost_per_distance_unit: null,
                        },
                        {
                            fuel_transaction_code: '53b7d0dd',
                            license_plate: 'BA8954',
                            volume: 33.73,
                            amount: 56610.37,
                            fuel_provider: 'Delta Panamá',
                            provider: null,
                            transaction_order: '46092',
                            transaction_datetime: '2021-06-10 07:23:15',
                            comment: null,
                            transaction_status: 'Transacción no validada',
                            odometer: null,
                            gps_event: null,
                            address: null,
                            account_name: null,
                            google_link: null,
                            code: 'e054',
                            fuel_type: '',
                            fuel_provider_code: '8add',
                            cost_per_volume_unit: 1678.34,
                            distance: null,
                            distance_per_volume_unit: null,
                            cost_per_distance_unit: null,
                        },
                        {
                            fuel_transaction_code: '5e41ce2a',
                            license_plate: 'BA8954',
                            volume: 33.73,
                            amount: 56610.37,
                            fuel_provider: 'Delta Panamá',
                            provider: null,
                            transaction_order: '46092',
                            transaction_datetime: '2021-06-10 07:23:15',
                            comment: null,
                            transaction_status: 'Transacción no validada',
                            odometer: null,
                            gps_event: null,
                            address: null,
                            account_name: null,
                            google_link: null,
                            code: 'e054',
                            fuel_type: '',
                            fuel_provider_code: '8add',
                            cost_per_volume_unit: 1678.34,
                            distance: null,
                            distance_per_volume_unit: null,
                            cost_per_distance_unit: null,
                        },
                        {
                            fuel_transaction_code: 'f50d90da',
                            license_plate: 'BA8954',
                            volume: 33.73,
                            amount: 56610.37,
                            fuel_provider: 'Delta Panamá',
                            provider: null,
                            transaction_order: '46092',
                            transaction_datetime: '2021-06-10 07:23:15',
                            comment: null,
                            transaction_status: 'Transacción no validada',
                            odometer: null,
                            gps_event: null,
                            address: null,
                            account_name: null,
                            google_link: null,
                            code: 'e054',
                            fuel_type: '',
                            fuel_provider_code: '8add',
                            cost_per_volume_unit: 1678.34,
                            distance: null,
                            distance_per_volume_unit: null,
                            cost_per_distance_unit: null,
                        },
                        {
                            fuel_transaction_code: '4333f275',
                            license_plate: 'BA8954',
                            volume: 33.73,
                            amount: 56610.37,
                            fuel_provider: 'Delta Panamá',
                            provider: null,
                            transaction_order: '46092',
                            transaction_datetime: '2021-06-10 07:23:15',
                            comment: null,
                            transaction_status: 'Transacción no validada',
                            odometer: null,
                            gps_event: null,
                            address: null,
                            account_name: null,
                            google_link: null,
                            code: 'e054',
                            fuel_type: '',
                            fuel_provider_code: '8add',
                            cost_per_volume_unit: 1678.34,
                            distance: null,
                            distance_per_volume_unit: null,
                            cost_per_distance_unit: null,
                        },
                        {
                            fuel_transaction_code: 'b1c06804',
                            license_plate: 'BA8954',
                            volume: 33.73,
                            amount: 56610.37,
                            fuel_provider: 'Delta Panamá',
                            provider: null,
                            transaction_order: '46092',
                            transaction_datetime: '2021-06-10 07:23:15',
                            comment: null,
                            transaction_status: 'Transacción no validada',
                            odometer: null,
                            gps_event: null,
                            address: null,
                            account_name: null,
                            google_link: null,
                            code: 'e054',
                            fuel_type: '',
                            fuel_provider_code: '8add',
                            cost_per_volume_unit: 1678.34,
                            distance: null,
                            distance_per_volume_unit: null,
                            cost_per_distance_unit: null,
                        },
                        {
                            fuel_transaction_code: '103ef813',
                            license_plate: 'BF2571',
                            volume: 9.97,
                            amount: 16297.76,
                            fuel_provider: 'Delta Panamá',
                            provider: null,
                            transaction_order: '9106327',
                            transaction_datetime: '2021-06-01 09:55:23',
                            comment: null,
                            transaction_status: 'Transacción no validada',
                            odometer: null,
                            gps_event: null,
                            address: null,
                            account_name: null,
                            google_link: null,
                            code: 'e054',
                            fuel_type: '',
                            fuel_provider_code: '8add',
                            cost_per_volume_unit: 1634.68,
                            distance: null,
                            distance_per_volume_unit: null,
                            cost_per_distance_unit: null,
                        },
                        {
                            fuel_transaction_code: '97e78369',
                            license_plate: 'BF2571',
                            volume: 9.97,
                            amount: 16297.76,
                            fuel_provider: 'Delta Panamá',
                            provider: null,
                            transaction_order: '9106327',
                            transaction_datetime: '2021-06-01 09:55:23',
                            comment: null,
                            transaction_status: 'Transacción no validada',
                            odometer: null,
                            gps_event: null,
                            address: null,
                            account_name: null,
                            google_link: null,
                            code: 'e054',
                            fuel_type: '',
                            fuel_provider_code: '8add',
                            cost_per_volume_unit: 1634.68,
                            distance: null,
                            distance_per_volume_unit: null,
                            cost_per_distance_unit: null,
                        },
                        {
                            fuel_transaction_code: '54162f0c',
                            license_plate: 'BF2571',
                            volume: 9.97,
                            amount: 16297.76,
                            fuel_provider: 'Delta Panamá',
                            provider: null,
                            transaction_order: '9106327',
                            transaction_datetime: '2021-06-01 09:55:23',
                            comment: null,
                            transaction_status: 'Transacción no validada',
                            odometer: null,
                            gps_event: null,
                            address: null,
                            account_name: null,
                            google_link: null,
                            code: 'e054',
                            fuel_type: '',
                            fuel_provider_code: '8add',
                            cost_per_volume_unit: 1634.68,
                            distance: null,
                            distance_per_volume_unit: null,
                            cost_per_distance_unit: null,
                        },
                        {
                            fuel_transaction_code: '410ef513',
                            license_plate: 'BF2571',
                            volume: 9.97,
                            amount: 16297.76,
                            fuel_provider: 'Delta Panamá',
                            provider: null,
                            transaction_order: '9106327',
                            transaction_datetime: '2021-06-01 09:55:23',
                            comment: null,
                            transaction_status: 'Transacción no validada',
                            odometer: null,
                            gps_event: null,
                            address: null,
                            account_name: null,
                            google_link: null,
                            code: 'e054',
                            fuel_type: '',
                            fuel_provider_code: '8add',
                            cost_per_volume_unit: 1634.68,
                            distance: null,
                            distance_per_volume_unit: null,
                            cost_per_distance_unit: null,
                        },
                        {
                            fuel_transaction_code: '0f57de9a',
                            license_plate: 'C01450620',
                            volume: 13.61,
                            amount: 27015.94,
                            fuel_provider: 'Delta Panamá',
                            provider: null,
                            transaction_order: '9106330',
                            transaction_datetime: '2021-06-01 15:17:38',
                            comment: null,
                            transaction_status: 'Transacción no validada',
                            odometer: null,
                            gps_event: null,
                            address: null,
                            account_name: null,
                            google_link: null,
                            code: 'e054',
                            fuel_type: '',
                            fuel_provider_code: '8add',
                            cost_per_volume_unit: 1985.01,
                            distance: null,
                            distance_per_volume_unit: null,
                            cost_per_distance_unit: null,
                        },
                        {
                            fuel_transaction_code: '6cf4fc92',
                            license_plate: 'C01450620',
                            volume: 13.61,
                            amount: 27015.94,
                            fuel_provider: 'Delta Panamá',
                            provider: null,
                            transaction_order: '9106330',
                            transaction_datetime: '2021-06-01 15:17:38',
                            comment: null,
                            transaction_status: 'Transacción no validada',
                            odometer: null,
                            gps_event: null,
                            address: null,
                            account_name: null,
                            google_link: null,
                            code: 'e054',
                            fuel_type: '',
                            fuel_provider_code: '8add',
                            cost_per_volume_unit: 1985.01,
                            distance: null,
                            distance_per_volume_unit: null,
                            cost_per_distance_unit: null,
                        },
                        {
                            fuel_transaction_code: '6d87de26',
                            license_plate: 'C01450620',
                            volume: 13.61,
                            amount: 27015.94,
                            fuel_provider: 'Delta Panamá',
                            provider: null,
                            transaction_order: '9106330',
                            transaction_datetime: '2021-06-01 15:17:38',
                            comment: null,
                            transaction_status: 'Transacción no validada',
                            odometer: null,
                            gps_event: null,
                            address: null,
                            account_name: null,
                            google_link: null,
                            code: 'e054',
                            fuel_type: '',
                            fuel_provider_code: '8add',
                            cost_per_volume_unit: 1985.01,
                            distance: null,
                            distance_per_volume_unit: null,
                            cost_per_distance_unit: null,
                        },
                        {
                            fuel_transaction_code: '22560096',
                            license_plate: 'C01450620',
                            volume: 13.61,
                            amount: 27015.94,
                            fuel_provider: 'Delta Panamá',
                            provider: null,
                            transaction_order: '9106330',
                            transaction_datetime: '2021-06-01 15:17:38',
                            comment: null,
                            transaction_status: 'Transacción no validada',
                            odometer: null,
                            gps_event: null,
                            address: null,
                            account_name: null,
                            google_link: null,
                            code: 'e054',
                            fuel_type: '',
                            fuel_provider_code: '8add',
                            cost_per_volume_unit: 1985.01,
                            distance: null,
                            distance_per_volume_unit: null,
                            cost_per_distance_unit: null,
                        },
                        {
                            fuel_transaction_code: '947b8b94',
                            license_plate: 'CT5003',
                            volume: 10.14,
                            amount: 17026.6,
                            fuel_provider: 'Delta Panamá',
                            provider: null,
                            transaction_order: '28268',
                            transaction_datetime: '2021-06-13 06:57:56',
                            comment: null,
                            transaction_status: 'Transacción no validada',
                            odometer: null,
                            gps_event: null,
                            address: null,
                            account_name: null,
                            google_link: null,
                            code: 'e054',
                            fuel_type: '',
                            fuel_provider_code: '8add',
                            cost_per_volume_unit: 1679.15,
                            distance: null,
                            distance_per_volume_unit: null,
                            cost_per_distance_unit: null,
                        },
                        {
                            fuel_transaction_code: '05d6990d',
                            license_plate: 'CT5003',
                            volume: 10.14,
                            amount: 17026.6,
                            fuel_provider: 'Delta Panamá',
                            provider: null,
                            transaction_order: '28268',
                            transaction_datetime: '2021-06-13 06:57:56',
                            comment: null,
                            transaction_status: 'Transacción no validada',
                            odometer: null,
                            gps_event: null,
                            address: null,
                            account_name: null,
                            google_link: null,
                            code: 'e054',
                            fuel_type: '',
                            fuel_provider_code: '8add',
                            cost_per_volume_unit: 1679.15,
                            distance: null,
                            distance_per_volume_unit: null,
                            cost_per_distance_unit: null,
                        },
                        {
                            fuel_transaction_code: '1c17f547',
                            license_plate: 'CT5003',
                            volume: 10.14,
                            amount: 17026.6,
                            fuel_provider: 'Delta Panamá',
                            provider: null,
                            transaction_order: '28268',
                            transaction_datetime: '2021-06-13 06:57:56',
                            comment: null,
                            transaction_status: 'Transacción no validada',
                            odometer: null,
                            gps_event: null,
                            address: null,
                            account_name: null,
                            google_link: null,
                            code: 'e054',
                            fuel_type: '',
                            fuel_provider_code: '8add',
                            cost_per_volume_unit: 1679.15,
                            distance: null,
                            distance_per_volume_unit: null,
                            cost_per_distance_unit: null,
                        },
                    ],
                },
            }
        },

        mounted() {
            const calendar = this.$refs.calendar as any

            if (calendar) this.title = calendar.title
        },

        created() {
            this.$store.commit('dashboard/title', 'Panel de control')

            const events = [] as any[]

            const { detail } = this.data

            for (const value of detail) {
                events.push({
                    name: value.license_plate,
                    // start: DateTime.fromSQL(value.transaction_datetime).toFormat('yyyy-LL-dd'),
                    start: value.transaction_datetime,
                    color: this.colorController(value.code),
                    data: value,
                })
            }

            this.events = events
        },

        methods: {
            colorController(code: string) {
                let result = ''

                switch (code) {
                    case 'ad8f':
                        result = 'red'
                        break
                    case 'baf8':
                        result = 'green'
                        break
                    case 'c4b2':
                        result = 'yellow'
                        break
                    case 'e054':
                        result = 'grey'
                        break
                }

                return result
            },

            eventController({ event }: any) {
                const { data } = event

                this.event = data
                this.view = true
            },

            moreController({ date }: any) {
                this.current = date
                this.type = 'day'
            },
        },
    })
</script>
